### ISSUE TITLE
The pagination isn't disabled when the list is less than 10

### ISSUE THREAD

**Issue by clive-machado** [kalimkhan7/tasks#1]
**Context:**
The pagination is enabled when the searched list is less than 10 items and nothing happens when I click next on commit e993ee02776e675a789fc64df04af735461233b6 in task4.

**Steps to recreate**
1) Search "test2".
2) The list is of three items.

**Solution or next steps:**
The pagination should be disabled when the list is less than 10.

**Comment by kalimkhan7** [comment]
Issues resolved and saved in new repository https://github.com/kalimkhan7/JSON-TO-TABLE
